export const employees = [
    {
        id: 1,
        fullName: "John Doe",
        occupation: "Software Engineer",
        department: "Engineering",
        dateOfEmployment: "2023-10-01",
        terminationDate: "2024-10-01",
    },
    {
        id: 2,
        fullName: "Jane Smith",
        occupation: "Product Manager",
        department: "Product",
        dateOfEmployment: "2022-05-15",
        terminationDate: null,
    },
    {
        id: 3,
        fullName: "Alice Johnson",
        occupation: "Data Scientist",
        department: "Data Science",
        dateOfEmployment: "2023-03-20",
        terminationDate: "2025-03-20",
    },
    {
        id: 4,
        fullName: "Bob Brown",
        occupation: "DevOps Engineer",
        department: "Engineering",
        dateOfEmployment: "2021-11-10",
        terminationDate: "2023-11-10",
    },
    {
        id: 5,
        fullName: "Charlie Davis",
        occupation: "UI/UX Designer",
        department: "Design",
        dateOfEmployment: "2024-01-01",
        terminationDate: null,
    },
    {
        id: 6,
        fullName: "Eva Green",
        occupation: "Marketing Specialist",
        department: "Marketing",
        dateOfEmployment: "2022-08-22",
        terminationDate: "2024-08-22",
    },
    {
        id: 7,
        fullName: "Frank White",
        occupation: "QA Engineer",
        department: "Engineering",
        dateOfEmployment: "2023-07-15",
        terminationDate: null,
    },
    {
        id: 8,
        fullName: "Grace Hall",
        occupation: "HR Manager",
        department: "Human Resources",
        dateOfEmployment: "2021-09-01",
        terminationDate: "2023-09-01",
    },
    {
        id: 9,
        fullName: "Henry Moore",
        occupation: "Sales Executive",
        department: "Sales",
        dateOfEmployment: "2023-12-01",
        terminationDate: null,
    },
    {
        id: 10,
        fullName: "Ivy Clark",
        occupation: "Financial Analyst",
        department: "Finance",
        dateOfEmployment: "2022-02-10",
        terminationDate: "2024-02-10",
    },
    {
        id: 11,
        fullName: "Jack Evans",
        occupation: "Backend Developer",
        department: "Engineering",
        dateOfEmployment: "2023-06-01",
        terminationDate: null,
    },
    {
        id: 12,
        fullName: "Karen Lee",
        occupation: "Frontend Developer",
        department: "Engineering",
        dateOfEmployment: "2024-02-15",
        terminationDate: null,
    },
    {
        id: 13,
        fullName: "Leo Martinez",
        occupation: "System Administrator",
        department: "IT",
        dateOfEmployment: "2021-12-01",
        terminationDate: "2023-12-01",
    },
    {
        id: 14,
        fullName: "Mia Garcia",
        occupation: "Content Writer",
        department: "Marketing",
        dateOfEmployment: "2023-09-10",
        terminationDate: null,
    },
    {
        id: 15,
        fullName: "Noah Wilson",
        occupation: "Business Analyst",
        department: "Business",
        dateOfEmployment: "2022-07-01",
        terminationDate: "2024-07-01",
    },
    {
        id: 16,
        fullName: "Olivia Taylor",
        occupation: "Recruitment Specialist",
        department: "Human Resources",
        dateOfEmployment: "2023-04-01",
        terminationDate: null,
    },
    {
        id: 17,
        fullName: "Paul Anderson",
        occupation: "Network Engineer",
        department: "IT",
        dateOfEmployment: "2022-10-01",
        terminationDate: "2025-10-01",
    },
    {
        id: 18,
        fullName: "Quinn Harris",
        occupation: "Customer Support",
        department: "Support",
        dateOfEmployment: "2023-08-01",
        terminationDate: null,
    },
    {
        id: 19,
        fullName: "Rachel King",
        occupation: "Legal Advisor",
        department: "Legal",
        dateOfEmployment: "2021-06-01",
        terminationDate: "2023-06-01",
    },
    {
        id: 20,
        fullName: "Sam Wright",
        occupation: "Project Manager",
        department: "Project Management",
        dateOfEmployment: "2027-11-01",
        terminationDate: null,
    },
];